"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {LatestOfficialNews} from "@/components/LatestOfficialNews";
import {ProjectMap} from "@/components/ProjectMap";
import {PublicSourceDrawer} from "@/components/PublicSourceDrawer";
import {downloadCsv,type PublicProject,type PublicSource} from "@/lib/public-data";

export type AluminumProject={id:string;name:string;country:string;status:"运营中"|"暂停";operator:string;ownership:string;stage:string;product:string;production:number|null;productionUnit:string;productionPeriod:string;productionBasis:string;guidance:string|null;capacity:string;reserve:string|null;sourceId:string};
export const aluminumSources:PublicSource[]=[
 {id:"al-rio-q3-25",tier:"A",source_type:"company_results",organization:"Rio Tinto",title:"Third Quarter Operations Review 2025",publication_date:"2025-10-14",verification_date:"2026-10-08",url:"https://www.riotinto.com/-/media/content/documents/invest/financial-news-and-performance/production/2025/2025-third-qor.pdf",locator:"Bauxite production table · Weipa and Gove",short_excerpt:"Q3 and nine-month marketable bauxite production by operation."},
 {id:"al-rio-gove",tier:"A",source_type:"company_operation_profile",organization:"Rio Tinto",title:"Gove operation profile",publication_date:"2026-02-01",verification_date:"2026-10-08",url:"https://www.riotinto.com/operations/anz/gove",locator:"2025 figures · production and ownership",short_excerpt:"2025 bauxite production and planned end of mining in 2029."},
 {id:"al-hydro-paragominas",tier:"A",source_type:"company_announcement",organization:"Norsk Hydro",title:"Mineração Paragominas marks 19 years",publication_date:"2026-03-01",verification_date:"2026-10-08",url:"https://www.hydro.com/br/br/imprensa/noticias/2026/mineracao-paragominas-celebra-19-anos-de-contribuicao-para-o-desenvolvimento-da-regiao/",locator:"2025 commercial bauxite volume",short_excerpt:"More than 10.5 Mt of bauxite sold to Alunorte in 2025."},
 {id:"al-alcoa-2025",tier:"A",source_type:"company_results",organization:"Alcoa",title:"Fourth Quarter and Full Year 2025 Results",publication_date:"2026-01-22",verification_date:"2026-10-08",url:"https://news.alcoa.com/press-releases/press-release-details/2026/Alcoa-Corporation-Reports-Fourth-Quarter-and-Full-Year-2025-Results/default.aspx",locator:"Alumina segment production and 2026 outlook",short_excerpt:"2025 alumina segment production and 2026 production outlook."},
 {id:"al-alcoa-juruti",tier:"A",source_type:"company_technical_disclosure",organization:"Alcoa",title:"March 2025 Investor Presentation",publication_date:"2025-03-12",verification_date:"2026-10-08",url:"https://investors.alcoa.com/files/doc_events/2025/Mar/12/March-2025-Investor-Presentation-vF.pdf",locator:"Bauxite production · Juruti",short_excerpt:"2024 Juruti bauxite production and Alumar operating capacity."},
 {id:"al-south32-ar25",tier:"A",source_type:"annual_report",organization:"South32",title:"Annual Report 2025",publication_date:"2025-08-28",verification_date:"2026-10-08",url:"https://www.south32.net/docs/default-source/annual-reporting-suite/2025/annual-report-2025.pdf",locator:"p. 91 · Worsley Alumina",short_excerpt:"FY25 saleable alumina production, ownership, guidance and nameplate capacity."},
 {id:"al-hydro-ar25",tier:"A",source_type:"annual_report",organization:"Norsk Hydro",title:"Integrated Annual Report 2025",publication_date:"2026-03-01",verification_date:"2026-10-08",url:"https://www.hydro.com/globalassets/06-investors/reports-and-presentations/annual-report/ar-2025/integrated-annual-report-2025.pdf",locator:"Bauxite & Alumina · Alunorte",short_excerpt:"Alunorte ownership, alumina production and nameplate capacity."},
 {id:"al-ega-h1-25",tier:"A",source_type:"company_results",organization:"Emirates Global Aluminium",title:"EGA reports resilient H1 2025 performance",publication_date:"2025-09-04",verification_date:"2026-10-08",url:"https://media.ega.ae/ega-reports-resilient-h1-financial-performance-with-industry-leading-aluminium-margins-and-strategic-progress-despite-guinea-supply-disruption-and-asset-write-down/",locator:"Al Taweelah production and Guinea supply disruption",short_excerpt:"H1 2025 alumina production and operational effect of Guinea supply disruption."},
];
export const aluminumProjects:AluminumProject[]=[
 {id:"weipa",name:"Weipa",country:"澳大利亚",status:"运营中",operator:"Rio Tinto",ownership:"Rio Tinto 100%",stage:"铝土矿开采",product:"可销售铝土矿",production:29.442,productionUnit:"Mt",productionPeriod:"2025 9M",productionBasis:"项目 100% · 年初至今",guidance:null,capacity:"Amrun/Andoom 运营体系；扩建研究中",reserve:"Amrun 已披露矿石储量 978 Mt",sourceId:"al-rio-q3-25"},
 {id:"gove",name:"Gove",country:"澳大利亚",status:"运营中",operator:"Rio Tinto",ownership:"Rio Tinto 100%",stage:"铝土矿开采",product:"可销售铝土矿",production:12.729,productionUnit:"Mt",productionPeriod:"2025",productionBasis:"项目 100% · 全年",guidance:"计划 2029 年结束铝土矿开采",capacity:"按剩余矿山寿命运营",reserve:null,sourceId:"al-rio-gove"},
 {id:"paragominas",name:"Paragominas",country:"巴西",status:"运营中",operator:"Norsk Hydro",ownership:"Hydro 100%",stage:"铝土矿开采 + 选矿",product:"铝土矿浆",production:10.5,productionUnit:"Mt",productionPeriod:"2025",productionBasis:"销售量 · 全年 · 超过",guidance:null,capacity:"244 km 管道输送至 Alunorte",reserve:null,sourceId:"al-hydro-paragominas"},
 {id:"juruti",name:"Juruti",country:"巴西",status:"运营中",operator:"Alcoa",ownership:"Alcoa 100%",stage:"铝土矿开采",product:"铝土矿",production:5.6,productionUnit:"Mdmt",productionPeriod:"2024",productionBasis:"项目 100% · 全年干吨",guidance:null,capacity:"约 6 Mtpa 运往 Alumar",reserve:null,sourceId:"al-alcoa-juruti"},
 {id:"worsley",name:"Worsley Alumina",country:"澳大利亚",status:"运营中",operator:"South32",ownership:"South32 86% / Japan Alumina Associates 10% / Sojitz 4%",stage:"铝土矿 + 氧化铝精炼",product:"可销售氧化铝",production:3.727,productionUnit:"Mt",productionPeriod:"FY2025",productionBasis:"South32 应占 86% · 财年",guidance:"FY2026 3.75 Mt（South32 应占）",capacity:"4.6 Mtpa 氧化铝（项目 100%）",reserve:null,sourceId:"al-south32-ar25"},
 {id:"alunorte",name:"Alunorte",country:"巴西",status:"运营中",operator:"Norsk Hydro",ownership:"Hydro 62%",stage:"氧化铝精炼",product:"冶金级氧化铝",production:6.1,productionUnit:"Mt",productionPeriod:"2025",productionBasis:"Hydro Bauxite & Alumina 披露口径",guidance:null,capacity:"6.3 Mtpa 氧化铝",reserve:null,sourceId:"al-hydro-ar25"},
 {id:"al-taweelah",name:"Al Taweelah Alumina",country:"阿联酋",status:"运营中",operator:"Emirates Global Aluminium",ownership:"EGA 100%",stage:"氧化铝精炼",product:"冶金级氧化铝",production:1.14,productionUnit:"Mt",productionPeriod:"2025 H1",productionBasis:"项目 100% · 半年",guidance:null,capacity:"约 2 Mtpa 氧化铝",reserve:null,sourceId:"al-ega-h1-25"},
 {id:"guinea-alumina-corporation",name:"Guinea Alumina Corporation",country:"几内亚",status:"暂停",operator:"Emirates Global Aluminium",ownership:"EGA 100%",stage:"铝土矿开采 + 出口",product:"铝土矿",production:null,productionUnit:"Mt",productionPeriod:"2025",productionBasis:"暂停期间",guidance:null,capacity:"2024 出口 10.81 Mt；不计作当前供应",reserve:null,sourceId:"al-ega-h1-25"},
];
export const aluminumEvents=[
 {projectId:"guinea-alumina-corporation",date:"2025-09-04",kind:"供应中断",headline:"几内亚业务中断影响原料供应",summary:"EGA 披露 Guinea 子公司供应中断及资产全额减记；Al Taweelah 改用其他来源铝土矿。",sourceId:"al-ega-h1-25"},
 {projectId:"weipa",date:"2025-05-22",kind:"扩建研究",headline:"Amrun 启动扩产前期工作",summary:"Rio Tinto 启动 Kangwinan 项目前期工作和最终工程研究，目标最早 2029 年首产。",sourceId:"al-rio-q3-25"},
 {projectId:"worsley",date:"2025-02-12",kind:"许可",headline:"矿山开发项目获得主要环境批准",summary:"新采区在 FY25 Q4 开始采矿，以改善 Worsley 的铝土矿供应。",sourceId:"al-south32-ar25"},
];
const loc:Record<string,{iso3:string;latitude:number;longitude:number;region:string}>={weipa:{iso3:"AUS",latitude:-12.63,longitude:141.88,region:"Queensland"},gove:{iso3:"AUS",latitude:-12.19,longitude:136.78,region:"Northern Territory"},paragominas:{iso3:"BRA",latitude:-3.25,longitude:-47.72,region:"Pará"},juruti:{iso3:"BRA",latitude:-2.16,longitude:-56.09,region:"Pará"},worsley:{iso3:"AUS",latitude:-33.33,longitude:116.08,region:"Western Australia"},alunorte:{iso3:"BRA",latitude:-1.52,longitude:-48.72,region:"Pará"},"al-taweelah":{iso3:"ARE",latitude:24.77,longitude:54.68,region:"Abu Dhabi"},"guinea-alumina-corporation":{iso3:"GIN",latitude:11.03,longitude:-13.76,region:"Boké"}};
export const aluminumSourceById=(id:string)=>aluminumSources.find(s=>s.id===id);export const aluminumProjectBySlug=(slug:string)=>aluminumProjects.find(p=>p.id===slug);
const mapProjects=aluminumProjects.map((p):PublicProject=>{const l=loc[p.id];return{id:`al-${p.id}`,slug:p.id,name:p.name,metal_id:"al",country:{iso3:l.iso3,name_zh:p.country,name_en:p.country},region:l.region,status:p.status==="运营中"?"operating":"suspended",operation_type:p.stage,production_stage:p.stage,primary_product:p.product,operator:p.operator,operator_source_id:p.sourceId,operator_missing_reason:null,location:{latitude:l.latitude,longitude:l.longitude,precision:"approximate",source_id:p.sourceId,locator:"公司披露资产所在区域的近似中心",basis:"仅用于区域定位，不代表矿权或设施边界。"},ownership:[],profile_source_id:p.sourceId,ownership_source_id:p.sourceId,verified_at:"2026-10-08"};});

export function AluminumDataProduct(){const[source,setSource]=useState<PublicSource|null>(null),[country,setCountry]=useState("all"),[status,setStatus]=useState("all"),[search,setSearch]=useState(""),[selectedId,setSelectedId]=useState("weipa"),[libraryOpen,setLibraryOpen]=useState(false);const filtered=useMemo(()=>aluminumProjects.filter(p=>{const q=search.trim().toLowerCase();return(!q||`${p.name} ${p.operator} ${p.country}`.toLowerCase().includes(q))&&(country==="all"||p.country===country)&&(status==="all"||p.status===status)}),[country,status,search]);const selected=aluminumProjectBySlug(selectedId)??aluminumProjects[0],countries=[...new Set(aluminumProjects.map(p=>p.country))];const openSource=(id:string)=>setSource(aluminumSourceById(id)??null);const exportRows=()=>downloadCsv("metals-atlas-aluminum-projects.csv",filtered.map(p=>({project:p.name,country:p.country,status:p.status,operator:p.operator,ownership:p.ownership,production_stage:p.stage,product:p.product,production:p.production,production_unit:p.productionUnit,production_period:p.productionPeriod,production_basis:p.productionBasis,guidance:p.guidance,capacity:p.capacity,reserve:p.reserve,source_url:aluminumSourceById(p.sourceId)?.url??null})));
 return <main className="terminal lithium-terminal aluminum-terminal"><section className="research-strip lithium-hero" aria-labelledby="aluminum-title"><div className="metal-ident"><span className="metal-symbol aluminum-symbol">Al</span><div><p>铝供给研究终端</p><h1 id="aluminum-title">Aluminum supply research</h1></div></div><dl className="research-stats lithium-stats"><div><dt>数据核验</dt><dd>2026-10-08</dd></div><div><dt>项目覆盖</dt><dd>8</dd></div><div><dt>运营项目</dt><dd>7</dd></div><div><dt>有产量事实</dt><dd>7</dd></div><div><dt>来源材料</dt><dd>8</dd></div></dl><div className="research-actions"><button type="button" onClick={()=>setLibraryOpen(true)}>来源索引 <span>8</span></button><button type="button" onClick={exportRows}>导出 CSV</button></div><p className="supply-thesis"><b>口径说明</b>铝土矿、氧化铝和原铝属于不同生产阶段，不直接相加；干吨、湿吨、项目 100% 与公司应占口径分别标注。</p></section><LatestOfficialNews metal="al"/>
 <section className="supply-workbench lithium-workbench"><div className="map-workspace"><div className="section-heading"><div><span>01 / 全球项目面</span><h2>铝产业链资产分布</h2></div><p>坐标为近似项目中心；点大小不表示产量。</p></div><ProjectMap projects={mapProjects.filter(m=>filtered.some(p=>p.id===m.slug))} selectedProjectId={`al-${selectedId}`} eventProjectIds={aluminumEvents.map(e=>`al-${e.projectId}`)} onSelect={id=>setSelectedId(id.replace(/^al-/,""))} ariaLabel="全球铝产业链项目地图"/><div className="map-legend"><span><i className="operating"/>运营中</span><span><i className="event-ring"/>有供给事件</span></div><div className="map-selection"><div><span>{selected.country} · {selected.status}</span><h3>{selected.name}</h3><p>{selected.operator} · {selected.stage}</p></div><dl><div><dt>产品</dt><dd>{selected.product}</dd></div><div><dt>产量</dt><dd>{selected.production===null?"待补":`${selected.production} ${selected.productionUnit}`}</dd></div><div><dt>产能/状态</dt><dd>{selected.capacity}</dd></div></dl><Link href={`/aluminum/projects/${selected.id}`}>打开项目档案 →</Link></div></div><aside className="event-stream"><div className="section-heading"><div><span>02 / 供给动态</span><h2>时间流</h2></div><p>按披露日期倒序</p></div><div className="event-stream-list">{aluminumEvents.map(e=><article key={e.projectId} className={`stream-event ${selectedId===e.projectId?"active":""}`} onClick={()=>setSelectedId(e.projectId)}><time>{e.date}</time><div className="event-kind">{e.kind}</div><h3>{aluminumProjectBySlug(e.projectId)?.name}</h3><h4>{e.headline}</h4><p>{e.summary}</p><button className="evidence-link" type="button" onClick={x=>{x.stopPropagation();openSource(e.sourceId)}}>来源 ↗</button></article>)}</div></aside></section>
 <section className="lithium-intro aluminum-intro"><div><span className="lithium-overline">AL / VALUE CHAIN</span><h2>从矿山到氧化铝，<br/>按阶段阅读。</h2></div><p>首批覆盖澳大利亚、巴西、几内亚和阿联酋的八个关键资产。没有可靠材料的单元格保持 null，并显示“待补”。</p></section>
 <section className="matrix-section lithium-matrix"><div className="section-heading"><div><span>03 / 项目研究矩阵</span><h2>铝土矿与氧化铝资产</h2></div><p>{filtered.length} / 8 个项目</p></div><div className="matrix-toolbar lithium-toolbar"><input aria-label="搜索铝项目" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索项目、国家或运营方"/><select aria-label="国家筛选" value={country} onChange={e=>setCountry(e.target.value)}><option value="all">全部国家</option>{countries.map(c=><option key={c}>{c}</option>)}</select><select aria-label="状态筛选" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option>运营中</option><option>暂停</option></select></div><div className="matrix-table-wrap lithium-table-wrap"><table className="research-matrix lithium-table"><thead><tr><th>项目</th><th>国家</th><th>运营方 / 权益</th><th>阶段 / 产品</th><th>最新产量</th><th>当前指引</th><th>产能 / 状态</th><th>储量</th><th>来源</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><Link href={`/aluminum/projects/${p.id}`}><b>{p.name}</b><span>{p.status}</span></Link></td><td>{p.country}</td><td><b>{p.operator}</b><small>{p.ownership}</small></td><td><b>{p.stage}</b><small>{p.product}</small></td><td>{p.production===null?<span className="missing-value">待补 / 暂停期间</span>:<><b>{p.production.toLocaleString()} {p.productionUnit}</b><small>{p.productionPeriod} · {p.productionBasis}</small></>}</td><td>{p.guidance??<span className="missing-value">待补 / 未披露</span>}</td><td>{p.capacity}</td><td>{p.reserve??<span className="missing-value">待补 / 本批未录入</span>}</td><td><button className="evidence-link" type="button" onClick={()=>openSource(p.sourceId)}>A级来源 ↗</button></td></tr>)}</tbody></table></div><div className="lithium-mobile-cards">{filtered.map(p=><article key={p.id}><header><div><b>{p.name}</b><span>{p.country} · {p.status}</span></div><button className="evidence-link" type="button" onClick={()=>openSource(p.sourceId)}>来源 ↗</button></header><p>{p.operator} · {p.stage}</p><dl><div><dt>最新产量</dt><dd>{p.production===null?"待补":`${p.production} ${p.productionUnit}`}</dd></div><div><dt>产能/状态</dt><dd>{p.capacity}</dd></div><div><dt>口径</dt><dd>{p.productionBasis}</dd></div></dl></article>)}</div></section>
 <section className="lithium-method"><div className="section-heading"><div><span>04 / 数据边界</span><h2>产业链阶段与吨位基础不混算</h2></div></div><div className="lithium-method-grid"><article><b>NULL ≠ 0</b><p>暂停或未披露不等于零产量。</p></article><article><b>阶段隔离</b><p>铝土矿、氧化铝及原铝分别保存。</p></article><article><b>吨位明确</b><p>干吨、湿吨和产品吨位不可直接替换。</p></article><article><b>权益明确</b><p>项目 100% 与公司应占数字不会混入同一总计。</p></article></div></section>
 {libraryOpen&&<div className="source-library-backdrop" onClick={()=>setLibraryOpen(false)}><section className="source-library" role="dialog" aria-modal="true" aria-label="铝来源索引" onClick={e=>e.stopPropagation()}><header><div><span>AL / 资料库</span><h2>铝证据索引</h2><p>8 份公司公告、年报和正式业绩材料。</p></div><button type="button" onClick={()=>setLibraryOpen(false)}>×</button></header><div>{aluminumSources.map(s=><button key={s.id} type="button" onClick={()=>{setLibraryOpen(false);setSource(s)}}><span className="tier tier-a">A</span><div><b>{s.title}</b><small>{s.organization} · {s.publication_date}</small><em>{s.locator}</em></div><i>查看 →</i></button>)}</div></section></div>}<PublicSourceDrawer source={source} onClose={()=>setSource(null)}/></main>;
}
