"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { LatestOfficialNews } from "@/components/LatestOfficialNews";
import { ProjectMap } from "@/components/ProjectMap";
import { PublicSourceDrawer } from "@/components/PublicSourceDrawer";
import { downloadCsv, type PublicProject, type PublicSource } from "@/lib/public-data";

export type NickelProject = {
  id:string; name:string; country:string; status:"运营中"|"开发中"|"暂停"; operator:string; ownership:string;
  stage:string; product:string; production:number|null; productionUnit:string; productionPeriod:string;
  productionBasis:string; guidance:string|null; capacity:string; reserve:string|null; sourceId:string;
};

export const nickelSources: PublicSource[] = [
  {id:"ni-vale-4q25",tier:"A",source_type:"company_results",organization:"Vale",title:"Vale's Production and Sales in 4Q25 and 2025",publication_date:"2026-01-27",verification_date:"2026-10-08",url:"https://vale.com/w/vales-production-and-sales-in-4q25-and-2025/-/categories/64919",locator:"Nickel production · Q4 2025 asset table",short_excerpt:"Onça Puma and Voisey's Bay quarterly production, plus group nickel production."},
  {id:"ni-vale-3q25",tier:"A",source_type:"company_results",organization:"Vale",title:"Production and Sales Report 3Q25",publication_date:"2025-10-21",verification_date:"2026-10-08",url:"https://vale.com/en/w/production-and-sales-report-3q25/-/categories/64922",locator:"Nickel · Canadian operations",short_excerpt:"Sudbury ore mined and operating update."},
  {id:"ni-glencore-fy25",tier:"A",source_type:"company_results",organization:"Glencore",title:"Full Year 2025 Production Report",publication_date:"2026-01-29",verification_date:"2026-10-08",url:"https://www.glencore.com/media-and-insights/news/full-year-2025-production-report",locator:"Nickel assets · Murrin Murrin",short_excerpt:"2025 own-sourced Murrin Murrin nickel production."},
  {id:"ni-eramet-fy25",tier:"A",source_type:"company_results",organization:"Eramet",title:"FY 2025 Results",publication_date:"2026-02-18",verification_date:"2026-10-08",url:"https://www.eramet.com/wp-content/uploads/2026/02/2026-18-02-Eramet-PR-FY-2025.pdf",locator:"Nickel · PT Weda Bay Nickel",short_excerpt:"100% ore sales and NPI production, with Eramet equity basis."},
  {id:"ni-eramet-rkab26",tier:"A",source_type:"company_announcement",organization:"Eramet",title:"Reaction to initial production and sales volumes granted to PT Weda Bay Nickel",publication_date:"2026-02-11",verification_date:"2026-10-08",url:"https://www.eramet.com/en/news/eramet-reaction-to-the-initial-production-and-sales-volumes-granted-by-the-indonesian-authorities-to-its-joint-venture-pt-weda-bay-nickel/",locator:"2026 initial RKAB notification",short_excerpt:"Initial 2026 mining and sales volume of 12 Mwmt; upward revision to be requested."},
  {id:"ni-vale-indonesia-3q25",tier:"A",source_type:"company_results",organization:"PT Vale Indonesia",title:"Strengthening Stability, Accelerating Growth",publication_date:"2025-11-24",verification_date:"2026-10-08",url:"https://vale.com/in/w/strengthening-stability-accelerating-growth-pt-vale-delivers-robust-performance-and-advances-indonesia-s-sustainable-nickel-future-1",locator:"Operational performance · 9M25",short_excerpt:"Sorowako nickel matte production for Q3 and nine months 2025."},
  {id:"ni-igo-fy25",tier:"A",source_type:"annual_report",organization:"IGO Limited",title:"Annual Report 2025",publication_date:"2025-08-28",verification_date:"2026-10-08",url:"https://www.igo.com.au/site/PDF/67675945-e230-4201-817e-c26dc33e2b32/2025AnnualReport",locator:"Nova Operation · FY25 production",short_excerpt:"Nova nickel in concentrate production and life-of-mine guidance."},
  {id:"ni-bhp-suspension",tier:"A",source_type:"company_announcement",organization:"BHP",title:"Western Australia Nickel to temporarily suspend operations",publication_date:"2024-07-11",verification_date:"2026-10-08",url:"https://www.bhp.com/news/media-centre/releases/2024/07/western-australia-nickel-to-temporarily-suspend-operations",locator:"Temporary suspension and review timing",short_excerpt:"Operations suspended from October 2024; decision review intended by February 2027."},
];

export const nickelProjects: NickelProject[] = [
  {id:"onca-puma",name:"Onça Puma",country:"巴西",status:"运营中",operator:"Vale Base Metals",ownership:"Vale 100%",stage:"红土镍采矿 + RKEF",product:"镍铁",production:10.0,productionUnit:"kt Ni",productionPeriod:"2025 Q4",productionBasis:"项目 100% · 季度成品镍",guidance:null,capacity:"40 ktpa Ni（两座炉）",reserve:null,sourceId:"ni-vale-4q25"},
  {id:"voiseys-bay",name:"Voisey's Bay",country:"加拿大",status:"运营中",operator:"Vale Base Metals",ownership:"Vale 100%",stage:"硫化矿采选 + 下游冶炼",product:"成品镍（自有矿源）",production:7.4,productionUnit:"kt Ni",productionPeriod:"2025 Q4",productionBasis:"项目矿源 · 季度成品镍",guidance:null,capacity:"待补 / 地下矿处于爬坡期",reserve:null,sourceId:"ni-vale-4q25"},
  {id:"sudbury",name:"Sudbury",country:"加拿大",status:"运营中",operator:"Vale Base Metals",ownership:"Vale 100%",stage:"多金属硫化矿采选冶",product:"成品镍 / 铜及副产品",production:null,productionUnit:"kt Ni",productionPeriod:"2025",productionBasis:"资产口径",guidance:null,capacity:"待补 / 未采用集团产量代替",reserve:null,sourceId:"ni-vale-3q25"},
  {id:"murrin-murrin",name:"Murrin Murrin",country:"澳大利亚",status:"运营中",operator:"Glencore",ownership:"Glencore 100%",stage:"红土镍矿 + HPAL",product:"镍金属",production:32.1,productionUnit:"kt Ni",productionPeriod:"2025",productionBasis:"自有矿源 · 全年",guidance:null,capacity:"待补 / 本批未录入",reserve:null,sourceId:"ni-glencore-fy25"},
  {id:"weda-bay",name:"Weda Bay",country:"印度尼西亚",status:"运营中",operator:"PT Weda Bay Nickel",ownership:"Eramet 38.7% / Tsingshan 51.3% / PT Antam 10%",stage:"红土镍采矿 + RKEF",product:"镍矿石 / NPI",production:35.8,productionUnit:"kt NPI",productionPeriod:"2025",productionBasis:"项目 100% · 全年 NPI",guidance:"2026 初始 RKAB 12 Mwmt 矿石；将申请上调",capacity:"矿石与 NPI 分阶段披露",reserve:null,sourceId:"ni-eramet-fy25"},
  {id:"sorowako",name:"Sorowako",country:"印度尼西亚",status:"运营中",operator:"PT Vale Indonesia",ownership:"PTVI：MIND ID 34% / Vale Canada 33.88% / 其他",stage:"红土镍采矿 + 火法冶炼",product:"镍锍",production:54.975,productionUnit:"kt Ni",productionPeriod:"2025 9M",productionBasis:"公司/运营资产 · 年初至今",guidance:null,capacity:"180–216 吨镍锍/日",reserve:null,sourceId:"ni-vale-indonesia-3q25"},
  {id:"nova",name:"Nova",country:"澳大利亚",status:"运营中",operator:"IGO Limited",ownership:"IGO 100%（2026 已宣布出售）",stage:"硫化矿采选",product:"镍精矿（含镍量）",production:16.371,productionUnit:"kt Ni",productionPeriod:"FY2025",productionBasis:"项目 100% · 全年精矿含镍",guidance:"矿山寿命期 15–18 ktpa Ni；预计 2026-12 季度结束",capacity:"待补 / 采用产量指引而非铭牌产能",reserve:null,sourceId:"ni-igo-fy25"},
  {id:"western-australia-nickel",name:"Western Australia Nickel",country:"澳大利亚",status:"暂停",operator:"BHP",ownership:"BHP 100%",stage:"矿山 + 选矿 + 冶炼 + 精炼一体化",product:"精炼镍 / 硫酸镍",production:null,productionUnit:"kt Ni",productionPeriod:"2025–2026",productionBasis:"暂停期间",guidance:"2027-02 前复核重启、继续暂停、出售或关闭",capacity:"暂停维护；不计作当前供应",reserve:null,sourceId:"ni-bhp-suspension"},
];

export const nickelEvents = [
  {projectId:"weda-bay",date:"2026-02-11",kind:"许可",headline:"2026 初始 RKAB 为 12 Mwmt",summary:"该许可量是矿石采销口径，不是含镍金属量；Eramet 表示将申请上调。",sourceId:"ni-eramet-rkab26"},
  {projectId:"onca-puma",date:"2026-01-27",kind:"产量更新",headline:"第二座炉推动 Q4 产量",summary:"Vale 披露 Onça Puma 2025 Q4 成品镍产量 10.0 kt，第二座炉已成功投运。",sourceId:"ni-vale-4q25"},
  {projectId:"nova",date:"2025-08-28",kind:"矿山寿命",headline:"预计 2026 年末结束生产",summary:"IGO 的 FY25 年报维持 Nova 生命周期产量指引，并指向 2026 年 12 月季度结束。",sourceId:"ni-igo-fy25"},
  {projectId:"western-australia-nickel",date:"2024-07-11",kind:"暂停决定",headline:"西澳镍业务宣布暂停维护",summary:"BHP 宣布相关业务将从 2024 年 10 月起暂停，并计划在 2027 年 2 月前复核；公告未给出 10 月内的具体生效日。",sourceId:"ni-bhp-suspension"},
];

const locations:Record<string,{iso3:string;latitude:number;longitude:number;region:string}> = {
  "onca-puma":{iso3:"BRA",latitude:-6.53,longitude:-51.05,region:"Pará"},"voiseys-bay":{iso3:"CAN",latitude:56.33,longitude:-62.10,region:"Labrador"},
  sudbury:{iso3:"CAN",latitude:46.49,longitude:-81.01,region:"Ontario"},"murrin-murrin":{iso3:"AUS",latitude:-28.82,longitude:121.89,region:"Western Australia"},
  "weda-bay":{iso3:"IDN",latitude:0.51,longitude:127.95,region:"North Maluku"},sorowako:{iso3:"IDN",latitude:-2.53,longitude:121.36,region:"South Sulawesi"},
  nova:{iso3:"AUS",latitude:-32.40,longitude:123.42,region:"Western Australia"},"western-australia-nickel":{iso3:"AUS",latitude:-27.28,longitude:120.52,region:"Western Australia"},
};
export const nickelSourceById=(id:string)=>nickelSources.find((item)=>item.id===id);
export const nickelProjectBySlug=(slug:string)=>nickelProjects.find((item)=>item.id===slug);
const mapProjects = nickelProjects.map((project):PublicProject=>{const l=locations[project.id];return {id:`ni-${project.id}`,slug:project.id,name:project.name,metal_id:"ni",country:{iso3:l.iso3,name_zh:project.country,name_en:project.country},region:l.region,status:project.status==="运营中"?"operating":project.status==="开发中"?"development":"suspended",operation_type:project.stage,production_stage:project.stage,primary_product:project.product,operator:project.operator,operator_source_id:project.sourceId,operator_missing_reason:null,location:{latitude:l.latitude,longitude:l.longitude,precision:"approximate",source_id:project.sourceId,locator:"公司披露资产所在区域的近似中心",basis:"仅用于区域定位，不代表矿权或设施边界。"},ownership:[],profile_source_id:project.sourceId,ownership_source_id:project.sourceId,verified_at:"2026-10-08"};});

export function NickelDataProduct(){
  const [source,setSource]=useState<PublicSource|null>(null),[country,setCountry]=useState("all"),[status,setStatus]=useState("all"),[search,setSearch]=useState(""),[selectedId,setSelectedId]=useState("onca-puma"),[libraryOpen,setLibraryOpen]=useState(false);
  const filtered=useMemo(()=>nickelProjects.filter((p)=>{const q=search.trim().toLowerCase();return(!q||`${p.name} ${p.operator} ${p.country}`.toLowerCase().includes(q))&&(country==="all"||p.country===country)&&(status==="all"||p.status===status)}),[country,status,search]);
  const selected=nickelProjectBySlug(selectedId)??nickelProjects[0], countries=[...new Set(nickelProjects.map((p)=>p.country))];
  const openSource=(id:string)=>setSource(nickelSourceById(id)??null);
  const exportRows=()=>downloadCsv("metals-atlas-nickel-projects.csv",filtered.map((p)=>({project:p.name,country:p.country,status:p.status,operator:p.operator,ownership:p.ownership,production_stage:p.stage,product:p.product,production:p.production,production_unit:p.productionUnit,production_period:p.productionPeriod,production_basis:p.productionBasis,guidance:p.guidance,capacity:p.capacity,reserve:p.reserve,source_url:nickelSourceById(p.sourceId)?.url??null})));
  return <main className="terminal lithium-terminal nickel-terminal">
    <section className="research-strip lithium-hero nickel-hero" aria-labelledby="nickel-title"><div className="metal-ident"><span className="metal-symbol nickel-symbol">Ni</span><div><p>镍供给研究终端</p><h1 id="nickel-title">Nickel supply research</h1></div></div><dl className="research-stats lithium-stats"><div><dt>数据核验</dt><dd>2026-10-08</dd></div><div><dt>项目覆盖</dt><dd>{nickelProjects.length}</dd></div><div><dt>运营项目</dt><dd>{nickelProjects.filter(p=>p.status==="运营中").length}</dd></div><div><dt>有产量事实</dt><dd>{nickelProjects.filter(p=>p.production!==null).length}</dd></div><div><dt>来源材料</dt><dd>{nickelSources.length}</dd></div></dl><div className="research-actions"><button type="button" onClick={()=>setLibraryOpen(true)}>来源索引 <span>{nickelSources.length}</span></button><button type="button" onClick={exportRows}>导出 CSV</button></div><p className="supply-thesis"><b>口径说明</b>矿石、精矿含镍、镍锍、镍铁和精炼镍分开呈现；季度、YTD、全年及项目 100% / 应占口径不混算。</p></section>
    <LatestOfficialNews metal="ni" />
    <section className="supply-workbench lithium-workbench"><div className="map-workspace"><div className="section-heading"><div><span>01 / 全球项目面</span><h2>镍资产分布与生产阶段</h2></div><p>坐标为近似项目中心；点大小不表示产量。</p></div><ProjectMap projects={mapProjects.filter(m=>filtered.some(p=>p.id===m.slug))} selectedProjectId={`ni-${selectedId}`} eventProjectIds={nickelEvents.map(e=>`ni-${e.projectId}`)} onSelect={(id)=>setSelectedId(id.replace(/^ni-/,""))} ariaLabel="全球镍项目地图"/><div className="map-legend"><span><i className="operating"/>运营中</span><span><i className="development"/>开发中</span><span><i className="event-ring"/>有供给事件</span></div><div className="map-selection"><div><span>{selected.country} · {selected.status}</span><h3>{selected.name}</h3><p>{selected.operator} · {selected.stage}</p></div><dl><div><dt>产品</dt><dd>{selected.product}</dd></div><div><dt>产量</dt><dd>{selected.production===null?"待补":`${selected.production} ${selected.productionUnit}`}</dd></div><div><dt>产能</dt><dd>{selected.capacity}</dd></div></dl><Link href={`/nickel/projects/${selected.id}`}>打开项目档案 →</Link></div></div>
      <aside className="event-stream"><div className="section-heading"><div><span>02 / 供给动态</span><h2>时间流</h2></div><p>按披露日期倒序</p></div><div className="event-stream-list">{nickelEvents.map(e=><article key={e.projectId} className={`stream-event ${selectedId===e.projectId?"active":""}`} onClick={()=>setSelectedId(e.projectId)}><time>{e.date}</time><div className="event-kind">{e.kind}</div><h3>{nickelProjectBySlug(e.projectId)?.name}</h3><h4>{e.headline}</h4><p>{e.summary}</p><button className="evidence-link" type="button" onClick={(x)=>{x.stopPropagation();openSource(e.sourceId)}}>来源 ↗</button></article>)}</div></aside></section>
    <section className="lithium-intro nickel-intro"><div><span className="lithium-overline">NI / SUPPLY CHAIN</span><h2>镍不是一个数字，<br/>而是一条产品链。</h2></div><p>首批覆盖八个关键资产，横跨硫化镍、红土镍、HPAL、RKEF、精矿、镍锍和精炼环节。页面只记录可回到公司正式材料的事实；缺失值保留为 null 并显示“待补”。</p></section>
    <section className="matrix-section lithium-matrix"><div className="section-heading"><div><span>03 / 项目研究矩阵</span><h2>镍资产、产量与供给状态</h2></div><p>{filtered.length} / {nickelProjects.length} 个项目</p></div><div className="matrix-toolbar lithium-toolbar"><input aria-label="搜索镍项目" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索项目、国家或运营方"/><select aria-label="国家筛选" value={country} onChange={e=>setCountry(e.target.value)}><option value="all">全部国家</option>{countries.map(c=><option key={c}>{c}</option>)}</select><select aria-label="状态筛选" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option>运营中</option><option>开发中</option><option>暂停</option></select></div>
      <div className="matrix-table-wrap lithium-table-wrap"><table className="research-matrix lithium-table"><thead><tr><th>项目</th><th>国家</th><th>运营方 / 权益</th><th>生产阶段 / 产品</th><th>最新产量</th><th>当前指引</th><th>产能 / 状态</th><th>储量</th><th>来源</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><Link href={`/nickel/projects/${p.id}`}><b>{p.name}</b><span>{p.status}</span></Link></td><td>{p.country}</td><td><b>{p.operator}</b><small>{p.ownership}</small></td><td><b>{p.stage}</b><small>{p.product}</small></td><td>{p.production===null?<span className="missing-value">待补 / 未以产能代替</span>:<><b>{p.production.toLocaleString()} {p.productionUnit}</b><small>{p.productionPeriod} · {p.productionBasis}</small></>}</td><td>{p.guidance??<span className="missing-value">待补 / 未披露或不适用</span>}</td><td>{p.capacity}</td><td>{p.reserve??<span className="missing-value">待补 / 本批未录入</span>}</td><td><button className="evidence-link" type="button" onClick={()=>openSource(p.sourceId)}>A级来源 ↗</button></td></tr>)}</tbody></table></div>
      <div className="lithium-mobile-cards">{filtered.map(p=><article key={p.id}><header><div><b>{p.name}</b><span>{p.country} · {p.status}</span></div><button className="evidence-link" type="button" onClick={()=>openSource(p.sourceId)}>来源 ↗</button></header><p>{p.operator} · {p.stage}</p><dl><div><dt>最新产量</dt><dd>{p.production===null?"待补":`${p.production} ${p.productionUnit}`}</dd></div><div><dt>产能/状态</dt><dd>{p.capacity}</dd></div><div><dt>口径</dt><dd>{p.productionBasis}</dd></div></dl></article>)}</div></section>
    <section className="lithium-method"><div className="section-heading"><div><span>04 / 数据边界</span><h2>不同阶段、产品与期间不混算</h2></div><p>每项事实关联具体来源材料</p></div><div className="lithium-method-grid"><article><b>NULL ≠ 0</b><p>暂停或未披露不等于零产量。</p></article><article><b>产品隔离</b><p>矿石、NPI、精矿含镍、镍锍和精炼镍分别保存。</p></article><article><b>期间明确</b><p>季度、九个月、财年与自然年均明确标注。</p></article><article><b>权益明确</b><p>项目 100% 与公司应占口径不会放在同一总计中。</p></article></div></section>
    {libraryOpen&&<div className="source-library-backdrop" onClick={()=>setLibraryOpen(false)}><section className="source-library" role="dialog" aria-modal="true" aria-label="镍来源索引" onClick={e=>e.stopPropagation()}><header><div><span>NI / 资料库</span><h2>镍证据索引</h2><p>{nickelSources.length} 份公司公告、年报和正式业绩材料。</p></div><button type="button" onClick={()=>setLibraryOpen(false)} aria-label="关闭资料库">×</button></header><div>{nickelSources.map(s=><button key={s.id} type="button" onClick={()=>{setLibraryOpen(false);setSource(s)}}><span className="tier tier-a">A</span><div><b>{s.title}</b><small>{s.organization} · {s.publication_date}</small><em>{s.locator}</em></div><i>查看 →</i></button>)}</div></section></div>}<PublicSourceDrawer source={source} onClose={()=>setSource(null)}/>
  </main>;
}
