"""phase 1a schema

Revision ID: 11403e40168f
Revises: 
Create Date: 2026-09-16 10:24:57.959612
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


revision: str = '11403e40168f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('name_zh', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3')
    )
    op.create_table('metals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name_zh', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('organization_name', sa.String(length=250), nullable=False),
    sa.Column('material_title', sa.String(length=500), nullable=False),
    sa.Column('material_url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=250), nullable=True),
    sa.Column('country_id', sa.String(length=36), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fiscal_year_start_month BETWEEN 1 AND 12', name='ck_company_fy_month'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('previewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_job_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=64), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('matched_record_id', sa.String(length=36), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('applied_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_job_id', 'sheet_name', 'row_number', name='uq_import_row')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('operator_company_id', sa.String(length=36), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_material_route', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['operator_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('guidance_observations',
    sa.Column('guidance_low', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('guidance_high', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('guidance_kind', sa.String(length=32), nullable=False),
    sa.Column('adjustment_type', sa.String(length=64), nullable=True),
    sa.Column('adjustment_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('metal_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=120), nullable=False),
    sa.Column('record_key', sa.String(length=200), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('original_unit', sa.String(length=32), nullable=True),
    sa.Column('normalized_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('normalized_unit', sa.String(length=32), nullable=False),
    sa.Column('missing_reason', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('calendar_basis', sa.String(length=32), nullable=False),
    sa.Column('fiscal_year_label', sa.String(length=32), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=32), nullable=False),
    sa.Column('ownership_basis', sa.String(length=32), nullable=False),
    sa.Column('production_stage', sa.String(length=64), nullable=False),
    sa.Column('source_published_at', sa.Date(), nullable=False),
    sa.Column('source_locator', sa.String(length=500), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("calendar_basis != 'fiscal_year' OR (fiscal_year_label IS NOT NULL AND fiscal_year_start_month BETWEEN 1 AND 12)", name='ck_guidance_fiscal_fields'),
    sa.CheckConstraint("calendar_basis IN ('calendar_year','fiscal_year')", name='ck_guidance_calendar_basis'),
    sa.CheckConstraint("guidance_kind IN ('initial','revision','maintained')", name='ck_guidance_kind'),
    sa.CheckConstraint("ownership_basis IN ('project_100','equity','attributable','consolidated','unknown')", name='ck_guidance_ownership_basis'),
    sa.CheckConstraint("period_type IN ('quarter','ytd','annual','other')", name='ck_guidance_period_type'),
    sa.CheckConstraint("review_status IN ('pending','approved','rejected')", name='ck_guidance_review_status'),
    sa.CheckConstraint('guidance_high IS NULL OR guidance_low IS NULL OR guidance_high >= guidance_low', name='ck_guidance_range'),
    sa.CheckConstraint('normalized_value IS NOT NULL OR missing_reason IS NOT NULL', name='ck_guidance_missing_reason'),
    sa.CheckConstraint('period_end >= period_start', name='ck_guidance_period_dates'),
    sa.ForeignKeyConstraint(['metal_id'], ['metals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'record_key', name='uq_guidance_source_record')
    )
    op.create_table('production_observations',
    sa.Column('is_cumulative', sa.Boolean(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('metal_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=120), nullable=False),
    sa.Column('record_key', sa.String(length=200), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('original_unit', sa.String(length=32), nullable=True),
    sa.Column('normalized_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('normalized_unit', sa.String(length=32), nullable=False),
    sa.Column('missing_reason', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('calendar_basis', sa.String(length=32), nullable=False),
    sa.Column('fiscal_year_label', sa.String(length=32), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=32), nullable=False),
    sa.Column('ownership_basis', sa.String(length=32), nullable=False),
    sa.Column('production_stage', sa.String(length=64), nullable=False),
    sa.Column('source_published_at', sa.Date(), nullable=False),
    sa.Column('source_locator', sa.String(length=500), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("calendar_basis != 'fiscal_year' OR (fiscal_year_label IS NOT NULL AND fiscal_year_start_month BETWEEN 1 AND 12)", name='ck_production_fiscal_fields'),
    sa.CheckConstraint("calendar_basis IN ('calendar_year','fiscal_year')", name='ck_production_calendar_basis'),
    sa.CheckConstraint("ownership_basis IN ('project_100','equity','attributable','consolidated','unknown')", name='ck_production_ownership_basis'),
    sa.CheckConstraint("period_type IN ('quarter','ytd','annual','other')", name='ck_production_period_type'),
    sa.CheckConstraint("review_status IN ('pending','approved','rejected')", name='ck_production_review_status'),
    sa.CheckConstraint('normalized_value IS NOT NULL OR missing_reason IS NOT NULL', name='ck_production_missing_reason'),
    sa.CheckConstraint('period_end >= period_start', name='ck_production_period_dates'),
    sa.ForeignKeyConstraint(['metal_id'], ['metals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'record_key', name='uq_production_source_record')
    )
    op.create_table('project_ownership',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ownership_pct >= 0 AND ownership_pct <= 100', name='ck_ownership_pct'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_ownership_dates'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'company_id', 'valid_from', name='uq_ownership_start')
    )
    op.create_table('reserve_observations',
    sa.Column('reserve_kind', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('ore_tonnage', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('grade_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('contained_metal_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('metal_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=120), nullable=False),
    sa.Column('record_key', sa.String(length=200), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('original_unit', sa.String(length=32), nullable=True),
    sa.Column('normalized_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('normalized_unit', sa.String(length=32), nullable=False),
    sa.Column('missing_reason', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('calendar_basis', sa.String(length=32), nullable=False),
    sa.Column('fiscal_year_label', sa.String(length=32), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=32), nullable=False),
    sa.Column('ownership_basis', sa.String(length=32), nullable=False),
    sa.Column('production_stage', sa.String(length=64), nullable=False),
    sa.Column('source_published_at', sa.Date(), nullable=False),
    sa.Column('source_locator', sa.String(length=500), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("calendar_basis != 'fiscal_year' OR (fiscal_year_label IS NOT NULL AND fiscal_year_start_month BETWEEN 1 AND 12)", name='ck_reserve_fiscal_fields'),
    sa.CheckConstraint("calendar_basis IN ('calendar_year','fiscal_year')", name='ck_reserve_calendar_basis'),
    sa.CheckConstraint("ownership_basis IN ('project_100','equity','attributable','consolidated','unknown')", name='ck_reserve_ownership_basis'),
    sa.CheckConstraint("period_type IN ('quarter','ytd','annual','other')", name='ck_reserve_period_type'),
    sa.CheckConstraint("reserve_kind IN ('reserve','resource')", name='ck_reserve_kind'),
    sa.CheckConstraint("review_status IN ('pending','approved','rejected')", name='ck_reserve_review_status'),
    sa.CheckConstraint('normalized_value IS NOT NULL OR missing_reason IS NOT NULL', name='ck_reserve_missing_reason'),
    sa.CheckConstraint('period_end >= period_start', name='ck_reserve_period_dates'),
    sa.ForeignKeyConstraint(['metal_id'], ['metals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'record_key', name='uq_reserve_source_record')
    )
    op.create_table('review_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_type', sa.String(length=32), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('import_row_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('before_payload', sa.JSON(), nullable=True),
    sa.Column('after_payload', sa.JSON(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_row_id'], ['import_rows.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_type', 'observation_id', name='uq_review_observation')
    )
    now = datetime(2026, 9, 16, tzinfo=timezone.utc)
    metals = sa.table('metals', sa.column('id'), sa.column('code'), sa.column('name_zh'), sa.column('name_en'), sa.column('enabled'), sa.column('created_at'), sa.column('updated_at'))
    op.bulk_insert(metals, [
        {'id': '10000000-0000-0000-0000-000000000001', 'code': 'Cu', 'name_zh': '铜', 'name_en': 'Copper', 'enabled': True, 'created_at': now, 'updated_at': now},
        {'id': '10000000-0000-0000-0000-000000000002', 'code': 'Al', 'name_zh': '铝', 'name_en': 'Aluminium', 'enabled': True, 'created_at': now, 'updated_at': now},
        {'id': '10000000-0000-0000-0000-000000000003', 'code': 'Pb', 'name_zh': '铅', 'name_en': 'Lead', 'enabled': True, 'created_at': now, 'updated_at': now},
        {'id': '10000000-0000-0000-0000-000000000004', 'code': 'Zn', 'name_zh': '锌', 'name_en': 'Zinc', 'enabled': True, 'created_at': now, 'updated_at': now},
        {'id': '10000000-0000-0000-0000-000000000005', 'code': 'Ni', 'name_zh': '镍', 'name_en': 'Nickel', 'enabled': True, 'created_at': now, 'updated_at': now},
        {'id': '10000000-0000-0000-0000-000000000006', 'code': 'Sn', 'name_zh': '锡', 'name_en': 'Tin', 'enabled': True, 'created_at': now, 'updated_at': now},
        {'id': '10000000-0000-0000-0000-000000000007', 'code': 'Li', 'name_zh': '锂', 'name_en': 'Lithium', 'enabled': True, 'created_at': now, 'updated_at': now},
    ])
    countries = sa.table('countries', sa.column('id'), sa.column('iso2'), sa.column('iso3'), sa.column('name_zh'), sa.column('name_en'), sa.column('region'), sa.column('created_at'), sa.column('updated_at'))
    op.bulk_insert(countries, [
        {'id': '20000000-0000-0000-0000-000000000001', 'iso2': 'CL', 'iso3': 'CHL', 'name_zh': '智利', 'name_en': 'Chile', 'region': 'South America', 'created_at': now, 'updated_at': now},
        {'id': '20000000-0000-0000-0000-000000000002', 'iso2': 'US', 'iso3': 'USA', 'name_zh': '美国', 'name_en': 'United States', 'region': 'North America', 'created_at': now, 'updated_at': now},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_items')
    op.drop_table('reserve_observations')
    op.drop_table('project_ownership')
    op.drop_table('production_observations')
    op.drop_table('guidance_observations')
    op.drop_table('projects')
    op.drop_table('import_rows')
    op.drop_table('import_jobs')
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('metals')
    op.drop_table('countries')
    # ### end Alembic commands ###
